version: '3.8'

services:
  vending_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: vending_app
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - vending_network

networks:
  vending_network:
    external: true
